version: "3.8"
services:
  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production

  user:
    build:
      context: ./apps/users
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    environment:
      - NODE_ENV=production

  tailor-shop:
    build:
      context: ./apps/tailorshop-owners
      dockerfile: Dockerfile
    ports:
      - "3003:80"
    environment:
      - NODE_ENV=production
