version: "3.8"
services:
  admin:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production

  user:
    build:
      context: ./frontend/users
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    environment:
      - NODE_ENV=production

  tailor-shop:
    build:
      context: ./frontend/tailorshop-owners
      dockerfile: Dockerfile
    ports:
      - "3003:80"
    environment:
      - NODE_ENV=production
