// data/profileComponentsData.js

import { predefinedServices } from "./Services.configs";

export const initialProfileComponents = [
  {
    id: "offers",
    title: "Offers",
    icon: "🏷️",
    enabled: false,
    contentFields: [
      { name: "title", label: "Offer Title", type: "text" },
      { name: "percentage", label: "Discount Rate (%)", type: "number" },
      { name: "startDate", label: "Start Date", type: "date" },
      { name: "endDate", label: "End Date", type: "date" },
      { name: "description", label: "Offer Description", type: "textarea" },
      { name: "image", label: "Offer Image", type: "image" },
    ],
    items: [],
  },
  {
    id: "designs",
    title: "Designs",
    icon: "🎨",
    enabled: false,
    contentFields: [
      { name: "title", label: "Design Title", type: "text" },
      { name: "price", label: "Design Price", type: "number" },
      { name: "description", label: "Design Description", type: "textarea" },
      { name: "image", label: "Design Image", type: "image" },
    ],
    items: [],
  },
  {
    id: "availability",
    title: "Availability",
    icon: "📅",
    enabled: false,
    contentFields: [
      {
        name: "day",
        label: "Day",
        type: "select",
        options: [
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday",
          "Saturday",
          "Sunday",
        ],
      },
      {
        name: "from",
        label: "Opening Time",
        type: "time",
        placeholder: "09:00 AM",
      },
      {
        name: "to",
        label: "Closing Time",
        type: "time",
        placeholder: "05:00 PM",
      },
      {
        name: "isOpen",
        label: "Available?",
        type: "checkbox",
        default: true,
      },
    ],
    items: [],
    // Additional availability-specific configuration
    timeFormat: "HH:mm", // 24-hour format for API
    displayFormat: "h:mm A", // 12-hour format for display
    timezone: "local", // or specify a timezone
    validation: {
      minHours: 1, // minimum hours between from and to
      maxHours: 24, // maximum hours between from and to
    },
  },
  {
    id: "address",
    title: "Address",
    icon: "📍",
    enabled: false,
    contentFields: [
      { name: "street", label: "Street Address", type: "text" },
      { name: "city", label: "City", type: "text" },
      { name: "state", label: "State/Province", type: "text" },
      { name: "zip", label: "Zip/Postal Code", type: "text" },
      { name: "country", label: "Country", type: "text" },
    ],
    items: [],
  },
  {
    id: "services",
    title: "Services",
    icon: "🛠️",
    enabled: false,
    contentFields: [{ name: "title", label: "Service Title", type: "text" }],
    items: [],
  },
  {
    id: "reviews",
    title: "Reviews",
    icon: "⭐",
    enabled: false,
    contentFields: [], // No fields as the business owner can't add reviews for themselves
    items: [],
    isClientGenerated: true, // Flag to indicate this is generated by clients, not the owner
  },
];

export const initialCustomerProfileComponents = [
  {
    id: "designs",
    title: "Designs",
    icon: "🎨",
    enabled: false,
    contentFields: [
      { name: "title", label: "Design Title", type: "text" },
      { name: "description", label: "Design Description", type: "textarea" },
      {
        name: "tags",
        label: "Design Tags",
        type: "select",
        options: predefinedServices,
        multiple: true,
      },
      { name: "image", label: "Design Image", type: "image" },
    ],
    items: [],
  },
  {
    id: "reviews",
    title: "Reviews",
    icon: "⭐",
    enabled: false,
    contentFields: [], // No fields as the business owner can't add reviews for themselves
    items: [],
    isClientGenerated: true, // Flag to indicate this is generated by clients, not the owner
  },
];
