// data/profileComponentsData.js

export const initialProfileComponents = [
  {
    id: "offers",
    title: "Offers",
    icon: "🏷️",
    enabled: false,
    contentFields: [
      { name: "title", label: "Offer Title", type: "text" },
      { name: "percentage", label: "Discount Rate (%)", type: "number" },
      { name: "startDate", label: "Start Date", type: "date" },
      { name: "endDate", label: "End Date", type: "date" },
      { name: "description", label: "Offer Description", type: "textarea" },
      { name: "image", label: "Offer Image", type: "image" },
    ],
    items: [],
  },
  {
    id: "designs",
    title: "Designs",
    icon: "🎨",
    enabled: false,
    contentFields: [
      { name: "title", label: "Design Title", type: "text" },
      { name: "price", label: "Design Price", type: "number" },
      { name: "description", label: "Design Description", type: "textarea" },
      { name: "image", label: "Design Image", type: "image" },
    ],
    items: [],
  },
  {
    id: "availability",
    title: "Availability",
    icon: "📅",
    enabled: false,
    contentFields: [
      { name: "day", label: "Day", type: "text" },
      { name: "hours", label: "Hours", type: "text" },
    ],
    items: [],
  },
  {
    id: "address",
    title: "Address",
    icon: "📍",
    enabled: false,
    contentFields: [
      { name: "street", label: "Street Address", type: "text" },
      { name: "city", label: "City", type: "text" },
      { name: "state", label: "State/Province", type: "text" },
      { name: "zip", label: "Zip/Postal Code", type: "text" },
      { name: "country", label: "Country", type: "text" },
    ],
    items: [],
  },
  {
    id: "services",
    title: "Services",
    icon: "🛠️",
    enabled: false,
    contentFields: [
      { name: "title", label: "Service Title", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "price", label: "Price", type: "text" },
    ],
    items: [],
  },
  {
    id: "reviews",
    title: "Reviews",
    icon: "⭐",
    enabled: false,
    contentFields: [], // No fields as the business owner can't add reviews for themselves
    items: [],
    isClientGenerated: true, // Flag to indicate this is generated by clients, not the owner
  },
];
