name: CI/CD with terraform
on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
  AWS_TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
  AWS_SSH_KEY_PRIVATE: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
  AWS_SSH_KEY_PUBLIC: ${{ secrets.AWS_SSH_KEY_PUBLIC }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=${{ secrets.AWS_TF_STATE_BUCKET_NAME }}" -backend-config="region=${{ secrets.AWS_REGION }}"
        working-directory: ./terraform

      - name: Terraform plan
        id: plan
        run: |-
          terraform plan \
          -var="aws_region=${{ secrets.AWS_REGION }}" \
          -var="aws_ssh_key_private=${{ secrets.AWS_SSH_KEY_PRIVATE }}" \
          -var="aws_ssh_key_public=${{ secrets.AWS_SSH_KEY_PUBLIC }}" \
          -var="key_name=deploy-key" \
          -out=PLAN
        working-directory: ./terraform

      - name: Terraform apply
        id: apply
        run: terraform apply PLAN
        working-directory: ./terraform
