name: Deploy React Application with HTTPS
on:
  push:
    branches:
      - dev
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL || 'https://needle360.online' }}
        run: |
          docker build -t rizz336/needle360-frontend:$GITHUB_SHA \
            --build-arg VITE_API_URL=$VITE_API_URL \
            -f Dockerfile .
          docker tag rizz336/needle360-frontend:$GITHUB_SHA rizz336/needle360-frontend:latest
          docker push rizz336/needle360-frontend:$GITHUB_SHA
          docker push rizz336/needle360-frontend:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Clean up old containers
        run: |
          docker stop needle360-frontend-container || true
          docker rm needle360-frontend-container || true
          docker image prune -f
          docker container prune -f
      - name: Check port availability
        run: |
          if sudo lsof -i :80; then sudo fuser -k 80/tcp || true; fi
          if sudo lsof -i :443; then sudo fuser -k 443/tcp || true; fi
          sleep 2
      - name: Create SSL directories if needed
        run: |
          sudo mkdir -p /etc/ssl/needle360
          sudo mkdir -p /etc/ssl/private
      - name: Verify SSL certificates exist
        run: |
          if [ ! -f "/etc/ssl/needle360/needle360.online.crt" ]; then
            echo "SSL certificate not found at /etc/ssl/needle360/needle360.online.crt"
            exit 1
          fi
          if [ ! -f "/etc/ssl/needle360/needle360.online.key" ]; then
            echo "SSL key not found at /etc/ssl/needle360/needle360.online.key"
            exit 1
          fi
      - name: Pull new image
        run: docker pull rizz336/needle360-frontend:latest

      - name: Run container
        run: |
          docker run -d \
            -p 80:80 \
            -p 443:443 \
            -v /etc/ssl/needle360:/etc/ssl/needle360:ro \
            --name needle360-frontend-container \
            --restart unless-stopped \
            --link needle360-backend-container \
            rizz336/needle360-frontend:latest
      - name: Verify deployment
        run: |
          sleep 10  # Give Nginx more time to start
          curl -k -I https://localhost || {
            echo "HTTPS deployment verification failed"
            docker logs needle360-frontend-container
            exit 1
          }
