name: Deploy React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t needle360-frontend -f Dockerfile .
          docker tag needle360-frontend rizz336/needle360-frontend
          docker push rizz336/needle360-frontend

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: docker pull rizz336/needle360-frontend

      - name: Deploy Admin App
        run: |
          if [ "$(docker ps -aq -f name=needle360-frontend-admin-container)" ]; then
            docker stop needle360-frontend-admin-container
            docker rm needle360-frontend-admin-container
          fi
          docker run -d \
            -p 8085:80 \
            --name needle360-frontend-admin-container \
            -e APP_ENV="admin" \
            rizz336/needle360-frontend

      - name: Deploy Tailor Shop Owners App
        run: |
          if [ "$(docker ps -aq -f name=needle360-frontend-tailorshop-container)" ]; then
            docker stop needle360-frontend-tailorshop-container
            docker rm needle360-frontend-tailorshop-container
          fi
          docker run -d \
            -p 8086:80 \
            --name needle360-frontend-tailorshop-container \
            -e APP_ENV="tailorshop-owners" \
            rizz336/needle360-frontend

      - name: Deploy Users App
        run: |
          if [ "$(docker ps -aq -f name=needle360-frontend-users-container)" ]; then
            docker stop needle360-frontend-users-container
            docker rm needle360-frontend-users-container
          fi
          docker run -d \
            -p 8087:80 \
            --name needle360-frontend-users-container \
            -e APP_ENV="users" \
            rizz336/needle360-frontend
