name: Deploy React Applications

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for admin app
        run: |
          docker build -t needle360-frontend:latest  . --build.arg NODE_ENV=production
          docker tag needle360-frontend:latest needle360-frontend:admin
          docker push needle360-frontend:admin

      - name: Build Docker image for tailorshop-owners app
        run: |
          docker build -t needle360-frontend:latest . --build.arg NODE_ENV=production
          docker tag needle360-frontend:latest needle360-frontend:tailorshop-owners
          docker push needle360-frontend:tailorshop-owners

      - name: Build Docker image for users app
        run: |
          docker build -t needle360-frontend:latest  . --build.arg NODE_ENV=production
          docker tag needle360-frontend:latest needle360-frontend:users
          docker push needle360-frontend:users

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image for admin app
        run: |
          docker pull rizz336/needle360-frontend:admin

      - name: Stop and Remove Old Container for admin app
        run: |
          if [ "$(docker ps -aq -f name=needle360-frontend-admin-container)" ]; then
            docker stop needle360-frontend-admin-container
            docker rm needle360-frontend-admin-container
          fi

      - name: Run Docker Container for admin app
        run: |
          docker run -d \
            -p 4000:4000 \
            --name needle360-frontend-admin-container \
            -e MONGODB_PASSWORD="${{ secrets.MONGODB_PASSWORD }}" \
            -e APP_ENV="admin" \
            rizz336/needle360-frontend:admin

      - name: Pull Docker Image for tailorshop-owners app
        run: |
          docker pull rizz336/needle360-frontend:tailorshop-owners

      - name: Stop and Remove Old Container for tailorshop-owners app
        run: |
          if [ "$(docker ps -aq -f name=needle360-frontend-tailorshop-owners-container)" ]; then
            docker stop needle360-frontend-tailorshop-owners-container
            docker rm needle360-frontend-tailorshop-owners-container
          fi

      - name: Run Docker Container for tailorshop-owners app
        run: |
          docker run -d \
            -p 4001:4000 \
            --name needle360-frontend-tailorshop-owners-container \
            -e MONGODB_PASSWORD="${{ secrets.MONGODB_PASSWORD }}" \
            -e APP_ENV="tailorshop-owners" \
            rizz336/needle360-frontend:tailorshop-owners

      - name: Pull Docker Image for users app
        run: |
          docker pull rizz336/needle360-frontend:users

      - name: Stop and Remove Old Container for users app
        run: |
          if [ "$(docker ps -aq -f name=needle360-frontend-users-container)" ]; then
            docker stop needle360-frontend-users-container
            docker rm needle360-frontend-users-container
          fi

      - name: Run Docker Container for users app
        run: |
          docker run -d \
            -p 4002:4000 \
            --name needle360-frontend-users-container \
            -e MONGODB_PASSWORD="${{ secrets.MONGODB_PASSWORD }}" \
            -e APP_ENV="users" \
            rizz336/needle360-frontend:users
