name: Deploy React Application with HTTPS

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Validate Environment Variables
        run: |
          echo "=== ENVIRONMENT VALIDATION ==="
          if [ -z "${{ secrets.VITE_API_URL }}" ]; then
            echo "❌ Error: VITE_API_URL is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}" ]; then
            echo "❌ Error: VITE_STRIPE_PUBLISHABLE_KEY is not set"
            exit 1
          fi
          echo "✅ VITE_API_URL: ${{ secrets.VITE_API_URL }}"
          echo "✅ VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY:0:20}..."

      - name: Generate build version
        run: |
          echo "GITHUB_SHA=$GITHUB_SHA" >> $GITHUB_ENV
          echo "$GITHUB_SHA" > version.txt

      - name: Build and Push Docker Image
        run: |
          echo "=== DOCKER BUILD ==="
          docker build \
            --no-cache \
            --build-arg VITE_API_URL="${{ secrets.VITE_API_URL }}" \
            --build-arg VITE_STRIPE_PUBLISHABLE_KEY="${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY }}" \
            --build-arg BUILD_VERSION=$GITHUB_SHA \
            --progress=plain \
            -t rizz336/needle360-frontend:$GITHUB_SHA \
            -t rizz336/needle360-frontend:latest \
            -f Dockerfile .
            
          echo "=== DOCKER PUSH ==="
          docker push rizz336/needle360-frontend:$GITHUB_SHA
          docker push rizz336/needle360-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Clean up environment
        run: |
          echo "=== CLEANUP ==="
          docker stop needle360-frontend-container || true
          docker rm needle360-frontend-container || true
          docker system prune -af
          docker volume prune -f

      - name: Verify ports
        run: |
          echo "=== PORT CHECK ==="
          sudo lsof -i :80 -t | xargs -r sudo kill -9
          sudo lsof -i :443 -t | xargs -r sudo kill -9
          sleep 3

      - name: Pull latest image
        run: |
          echo "=== PULL IMAGE ==="
          docker pull rizz336/needle360-frontend:latest

      - name: Deploy container
        run: |
          echo "=== DEPLOYMENT ==="
          docker run -d \
            -p 80:80 \
            -p 443:443 \
            -v /home/ubuntu/needle360/ssl:/etc/ssl/needle360:ro \
            --name needle360-frontend-container \
            --restart unless-stopped \
            --network needle360-network \
            -e NODE_ENV=production \
            --health-cmd="curl -f http://localhost/version || exit 1" \
            --health-interval=30s \
            --health-timeout=5s \
            --health-retries=5 \
            --health-start-period=10s \
            rizz336/needle360-frontend:latest

      - name: Verify deployment
        run: |
          echo "=== VERIFICATION ==="
          sleep 10
          echo "Container status:"
          docker ps -a | grep needle360-frontend-container

          echo "Health status:"
          docker inspect --format='{{json .State.Health}}' needle360-frontend-container

          echo "Version check:"
          CONTAINER_VERSION=$(docker exec needle360-frontend-container cat /usr/share/nginx/html/version.txt)
          echo "Container version: $CONTAINER_VERSION"
          echo "Expected version: $GITHUB_SHA"

          if [ "$CONTAINER_VERSION" != "$GITHUB_SHA" ]; then
            echo "❌ Version mismatch detected"
            exit 1
          fi

          echo "✅ Deployment verified"
