name: Deploy React Application

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important to get all history for checksums

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Verify package-lock.json exists
        run: |
          if [ ! -f "package-lock.json" ]; then
            echo "package-lock.json not found! Generating it..."
            npm install
          fi
          ls -la package-lock.json

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL || 'http://13.61.16.74:4000' }}
        run: |
          docker build -t rizz336/needle360-frontend:$GITHUB_SHA \
            --build-arg VITE_API_URL=$VITE_API_URL \
            -f Dockerfile .
          docker tag rizz336/needle360-frontend:$GITHUB_SHA rizz336/needle360-frontend:latest
          docker push rizz336/needle360-frontend:$GITHUB_SHA
          docker push rizz336/needle360-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Clean Up Disk Space
        run: |
          docker image prune -f || true
          docker container prune -f || true
          rm -rf /root/.npm/_cacache || true
          df -h

      - name: Check Docker Access
        run: docker ps || { echo "Docker not accessible"; exit 1; }

      - name: Verify Backend
        run: |
          curl -f ${{ secrets.VITE_API_URL || 'http://13.61.16.74:4000' }} || \
          { echo "Backend not accessible, proceeding anyway"; true; }

      - name: Check Port 5173 Availability
        run: |
          if sudo netstat -tuln | grep :5173; then
            echo "Port 5173 is in use, attempting to free it"
            sudo fuser -k 5173/tcp || true
            sleep 2
          fi

      - name: Pull Image
        run: docker pull rizz336/needle360-frontend:latest

      - name: Stop and Remove Old Container
        run: |
          docker stop needle360-frontend-container || true
          docker rm needle360-frontend-container || true
          sleep 2

      - name: Run New Container
        run: |
          docker run -d \
            -p 80:80 \
            --name needle360-frontend-container \
            --restart unless-stopped \
            rizz336/needle360-frontend:latest

      - name: Verify Container Running
        run: |
          sleep 10
          if ! docker ps | grep needle360-frontend-container; then
            echo "Container not running, checking logs..."
            docker logs needle360-frontend-container || true
            exit 1
          fi

      - name: Verify Nginx
        run: |
          sleep 5
          docker exec needle360-frontend-container nginx -t || \
          { echo "Nginx config error"; docker logs needle360-frontend-container; exit 1; }
          curl -I http://localhost || \  # Changed from http://localhost:5173
          { echo "Nginx not responding"; docker logs needle360-frontend-container; exit 1; }
