name: Build and Deploy Frontend Apps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build admin
        working-directory: apps/admin
        run: |
          npm install
          npm run build

      - name: Install dependencies and build user
        working-directory: apps/users
        run: |
          npm install
          npm run build

      - name: Install dependencies and build tailor-shop
        working-directory: apps/tailorshop-owners
        run: |
          npm install
          npm run build

      - name: Deploy to Docker
        run: docker-compose up --build -d
