name: Deploy React Applications

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for admin app
        run: |
          docker build -t needle360-frontend:latest -f ./admin/Dockerfile .
          docker tag needle360-frontend:latest needle360-frontend:admin
          docker push needle360-frontend:admin

      - name: Build Docker image for tailorshop-owners app
        run: |
          docker build -t needle360-frontend:latest -f ./tailorshop-owners/Dockerfile .
          docker tag needle360-frontend:latest needle360-frontend:tailorshop-owners
          docker push needle360-frontend:tailorshop-owners

      - name: Build Docker image for users app
        run: |
          docker build -t needle360-frontend:latest -f ./users/Dockerfile .
          docker tag needle360-frontend:latest needle360-frontend:users
          docker push needle360-frontend:users

  deploy:
    needs: build
    runs-on: self-hosted
    strategy:
      matrix:
        app: [admin, tailorshop-owners, users]
    steps:
      - name: Pull Docker Image
        run: |
          docker pull rizz336/needle360-frontend:${{ matrix.app }}

      - name: Stop and Remove Old Container
        run: |
          if [ "$(docker ps -aq -f name=needle360-frontend-${{ matrix.app }}-container)" ]; then
            docker stop needle360-frontend-${{ matrix.app }}-container
            docker rm needle360-frontend-${{ matrix.app }}-container
          fi

      - name: Run Docker Container
        run: |
          PORT=$(case ${{ matrix.app }} in
            admin) echo 4000 ;;
            tailorshop-owners) echo 4001 ;;
            users) echo 4002 ;;
            *) echo 4000 ;;
            esac)
          docker run -d \
            -p $PORT:4000 \
            --name needle360-frontend-${{ matrix.app }}-container \
            -e MONGODB_PASSWORD="${{ secrets.MONGODB_PASSWORD }}" \
            -e APP_ENV="${{ matrix.app }}" \
            rizz336/needle360-frontend:${{ matrix.app }}
