name: Deploy React Application with HTTPS
on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL || 'https://needle360.online' }}
        run: |
          docker build -t rizz336/needle360-frontend:$GITHUB_SHA \
            --build-arg VITE_API_URL=$VITE_API_URL \
            -f Dockerfile .
          docker tag rizz336/needle360-frontend:$GITHUB_SHA rizz336/needle360-frontend:latest
          docker push rizz336/needle360-frontend:$GITHUB_SHA
          docker push rizz336/needle360-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Clean up old containers and network
        run: |
          docker stop needle360-frontend-container || true
          docker rm needle360-frontend-container || true
          docker network rm needle360-network || true
          docker image prune -f
          docker container prune -f

      - name: Check port availability
        run: |
          if sudo lsof -i :80; then sudo fuser -k 80/tcp || true; fi
          if sudo lsof -i :443; then sudo fuser -k 443/tcp || true; fi
          sleep 2

      - name: Set up SSL directories with proper permissions
        run: |
          sudo mkdir -p /etc/ssl/needle360
          sudo mkdir -p /etc/ssl/private
          sudo chmod -R 755 /etc/ssl/needle360
          sudo chmod 750 /etc/ssl/private
          sudo chown -R $USER:$(id -gn) /etc/ssl/needle360 || true

      - name: Verify SSL certificates (with sudo)
        run: |
          if ! sudo test -f "/etc/ssl/needle360/needle360.online.crt"; then
            echo "SSL certificate not found at /etc/ssl/needle360/needle360.online.crt"
            sudo ls -la /etc/ssl/needle360/ || true
            exit 1
          fi
          if ! sudo test -f "/etc/ssl/needle360/needle360.online.key"; then
            echo "SSL key not found at /etc/ssl/needle360/needle360.online.key"
            sudo ls -la /etc/ssl/needle360/ || true
            exit 1
          fi
          echo "SSL files verified successfully"
          sudo ls -la /etc/ssl/needle360/ | grep -E 'needle360\.online\.(crt|key)'

      - name: Pull new image
        run: |
          docker pull rizz336/needle360-frontend:latest || {
            echo "Failed to pull image"
            exit 1
          }

      - name: Verify backend connectivity
        run: |
          # Check if backend container exists
          if ! docker inspect needle360-backend-container &> /dev/null; then
            echo "Backend container is not running"
            exit 1
          fi

          echo "Waiting for backend to be ready..."

          # Get backend container IP
          BACKEND_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' needle360-backend-container)
          BACKEND_PORT=4000  # Using the exposed port from your logs

          # Method 1: TCP port check (basic connectivity)
          if nc -zvw5 $BACKEND_IP $BACKEND_PORT; then
            echo "Backend port is responding (basic check)"
          else
            echo "Backend port not responding"
            exit 1
          fi

          # Method 2: HTTP health check (using published port)
          for i in {1..10}; do
            HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:$BACKEND_PORT/health || true)
            if [ "$HTTP_STATUS" = "200" ]; then
              echo "Backend health check passed"
              exit 0
            fi
            echo "Attempt $i: Backend not ready yet (HTTP $HTTP_STATUS)"
            sleep 5
          done

          echo "Backend health check failed after 10 attempts"
          echo "Container status:"
          docker ps -a | grep needle360-backend-container
          echo "Logs:"
          docker logs needle360-backend-container
          exit 1

      - name: Create Docker network
        run: |
          docker network create needle360-network --driver bridge || true
          docker network inspect needle360-network || {
            echo "Failed to create or inspect network"
            exit 1
          }

      - name: Deploy frontend container
        run: |
          docker run -d \
            -p 80:80 \
            -p 443:443 \
            -v /etc/ssl/needle360:/etc/ssl/needle360:ro \
            --name needle360-frontend-container \
            --restart unless-stopped \
            --network needle360-network \
            -e NODE_ENV=production \
            rizz336/needle360-frontend:latest || {
              echo "Container failed to start"
              exit 1
            }

      - name: Verify deployment
        run: |
          echo "Waiting for frontend to be ready..."
          for i in {1..10}; do
            if curl -k -I https://localhost; then
              echo "Deployment verified successfully"
              exit 0
            fi
            echo "Attempt $i: Frontend not ready yet"
            sleep 5
          done
          echo "HTTPS deployment verification failed after 10 attempts"
          docker logs needle360-frontend-container
          exit 1
