name: Deploy React Application
on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
          docker build -t rizz336/needle360-frontend:$GITHUB_SHA \
            --build-arg VITE_API_URL=http://13.61.16.74:4000 \
            -f Dockerfile .
          docker tag rizz336/needle360-frontend:$GITHUB_SHA rizz336/needle360-frontend:latest
          docker push rizz336/needle360-frontend:$GITHUB_SHA
          docker push rizz336/needle360-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Check Docker Access
        run: docker ps

      - name: Pull Image
        run: |
          docker pull rizz336/needle360-frontend:latest || \
          (echo "Docker pull failed - checking permissions" && \
          sudo docker pull rizz336/needle360-frontend:latest)

      - name: Stop and Remove Old Container
        run: |
          docker stop needle360-frontend-container || true
          docker rm needle360-frontend-container || true

      - name: Run New Container
        run: |
          docker run -d \
            -p 80:5173 \
            --name needle360-frontend-container \
            -e VITE_API_URL=http://13.61.16.74:4000 \
            --restart unless-stopped \
            rizz336/needle360-frontend:latest

      - name: Verify Container Running
        run: docker ps | grep needle360-frontend-container
