name: Deploy React Application with HTTPS
on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL || 'https://needle360.online' }}
        run: |
          docker build -t rizz336/needle360-frontend:$GITHUB_SHA \
            --build-arg VITE_API_URL=$VITE_API_URL \
            -f Dockerfile .
          docker tag rizz336/needle360-frontend:$GITHUB_SHA rizz336/needle360-frontend:latest
          docker push rizz336/needle360-frontend:$GITHUB_SHA
          docker push rizz336/needle360-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Create docker network
        run: docker network create needle360-network || true

      - name: Clean up old frontend container
        run: |
          docker stop needle360-frontend-container || true
          docker rm needle360-frontend-container || true

      - name: Check port availability
        run: |
          if sudo lsof -i :80; then sudo fuser -k 80/tcp || true; fi
          if sudo lsof -i :443; then sudo fuser -k 443/tcp || true; fi
          sleep 2

      - name: Set up SSL directories with proper permissions
        run: |
          sudo mkdir -p /etc/ssl/needle360
          sudo mkdir -p /etc/ssl/private
          sudo chmod -R 755 /etc/ssl/needle360
          sudo chmod 750 /etc/ssl/private
          sudo chown -R $USER:$(id -gn) /etc/ssl/needle360 || true

      - name: Verify SSL certificates
        run: |
          if ! sudo test -f "/etc/ssl/needle360/needle360.online.crt"; then
            echo "SSL certificate not found at /etc/ssl/needle360/needle360.online.crt"
            sudo ls -la /etc/ssl/needle360/ || true
            exit 1
          fi
          if ! sudo test -f "/etc/ssl/needle360/needle360.online.key"; then
            echo "SSL key not found at /etc/ssl/needle360/needle360.online.key"
            sudo ls -la /etc/ssl/needle360/ || true
            exit 1
          fi
          echo "SSL files verified successfully"
          sudo ls -la /etc/ssl/needle360/ | grep -E 'needle360\.online\.(crt|key)'

      - name: Pull new images
        run: |
          docker pull rizz336/needle360-frontend:latest || {
            echo "Failed to pull frontend image"
            exit 1
          }

      - name: Verify backend status
        run: |
          echo "Checking if backend is ready..."
          for i in {1..3}; do
            if curl -s -f http://needle360.online:4000 >/dev/null; then
              echo "Backend is ready"
              break
            fi
            if [ $i -eq 3 ]; then
              echo "Backend is not ready, but continuing with frontend deployment"
            else
              echo "Attempt $i: Backend not ready yet, trying again..."
              sleep 5
            fi
          done

      - name: Deploy frontend container
        run: |
          docker run -d \
            -p 80:80 \
            -p 443:443 \
            -v ~/needle360/ssl:/etc/nginx/ssl \
            -e NGINX_SSL_CERT=/etc/nginx/ssl/combined.crt \
            -e NGINX_SSL_KEY=/etc/nginx/ssl/private.key \
            --name needle360-frontend-container \
            rizz336/needle360-frontend:latest

      - name: Verify deployment
        run: |
          echo "Waiting for frontend to be ready..."
          for i in {1..10}; do
            if curl -k -I https://needle360.online >/dev/null 2>&1; then
              echo "Frontend is ready"
              exit 0
            fi
            echo "Attempt $i: Frontend not ready yet"
            sleep 5
          done
          echo "Frontend did not become ready after 10 attempts"
          docker logs needle360-frontend-container
