name: Deploy React Application

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL || 'http://13.61.16.74:4000' }}
        run: |
          docker build -t rizz336/needle360-frontend:$GITHUB_SHA \
            --build-arg VITE_API_URL=$VITE_API_URL \
            -f Dockerfile .
          docker tag rizz336/needle360-frontend:$GITHUB_SHA rizz336/needle360-frontend:latest
          docker push rizz336/needle360-frontend:$GITHUB_SHA
          docker push rizz336/needle360-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Clean up old containers
        run: |
          docker stop needle360-frontend-container || true
          docker rm needle360-frontend-container || true
          docker image prune -f
          docker container prune -f

      - name: Check port 80 availability
        run: |
          if sudo lsof -i :80; then
            echo "Port 80 is in use, attempting to free it"
            sudo fuser -k 80/tcp || true
            sleep 2
          fi

      - name: Pull new image
        run: docker pull rizz336/needle360-frontend:latest

      - name: Run container
        run: |
          docker run -d \
            -p 80:80 \
            --name needle360-frontend-container \
            --restart unless-stopped \
            rizz336/needle360-frontend:latest

      - name: Verify deployment
        run: |
          sleep 5
          curl -I http://localhost || {
            echo "Deployment verification failed"
            docker logs needle360-frontend-container
            exit 1
          }
