name: Deploy React Application

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Frontend Image
        run: |
          docker build -t rizz336/needle360-frontend:latest \
            --build-arg VITE_API_URL=http://13.61.16.74:4000 \
            -f Dockerfile .
          docker push rizz336/needle360-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: docker pull rizz336/needle360-frontend:latest

      - name: Stop Existing Container
        run: docker stop needle360-frontend-container || true

      - name: Remove Existing Container
        run: docker rm needle360-frontend-container || true

      - name: Run Docker Container
        run: |
          docker run -d -p 80:80 --name needle360-frontend-container \
            -e VITE_API_URL=http://13.61.16.74:4000 \
            rizz336/needle360-frontend:latest
